# Pandas入門 Series

## Series
一列のリストのようなものにインデックスがある

データフレームはSeriseをまとめたもの

In [4]:
import pandas as pd
import numpy as np

In [5]:
s1 = pd.Series([90, 78, 65, 87, 72])
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [6]:
data = [90, 78, 65, 87, 72]

In [7]:
s1 = pd.Series(data)
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [17]:
# numpyを使ってインポート
import numpy as np
np_data = np.arange(1, 10, 2) # 配列作成 1から10までの奇数

In [18]:
s2 = pd.Series(np_data)
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [19]:
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [20]:
# データ型の確認
s1.dtypes

dtype('int64')

In [21]:
# インデックス取得
s1.index

RangeIndex(start=0, stop=5, step=1)

0から始まり、5まで増えて1ずつ増えるインデックスとういことが分かります

In [24]:
# インデックスの変更
s1.index = ['sato', 'suzuki', 'takahashi', 'tanaka', 'ito']
s1

sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
dtype: int64

In [29]:
# indexが変更されているか確認
s1.index 

Index(['sato', 'suzuki', 'takahashi', 'tanaka', 'ito'], dtype='object')

## 辞書型データを使ってSerise作成

In [35]:
# keyとvalue形式で辞書型dataを変数に代入
dict01 = {'sato':90, 'suzuki':78, 'takahashi':65, 'tanaka':87, 'ito':72}

In [33]:
s3 = pd.Series(dict01)
s3

sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
dtype: int64

In [36]:
# シリーズの値を取得
s1.values

array([90, 78, 65, 87, 72])

In [37]:
# swuzukiの点数を取得
s1['suzuki']

78

In [39]:
# インデックス番号を指定して値を取得
s1[1]

78

In [40]:
# リストでインデックスを指定して値を取得
s1[['suzuki', 'tanaka']]

suzuki    78
tanaka    87
dtype: int64

In [41]:
s1[[1, 3]]

suzuki    78
tanaka    87
dtype: int64

In [45]:
# 80点より大きいものを抽出(大きいものはtrue そうでないものはfalse)
s1 > 80

sato          True
suzuki       False
takahashi    False
tanaka        True
ito          False
dtype: bool

In [46]:
# 80点より大きいものを抽出
s1[s1 > 80]

sato      90
tanaka    87
dtype: int64

In [48]:
# 80点以下のものを抽出
s1[s1 <= 80]

suzuki       78
takahashi    65
ito          72
dtype: int64

In [50]:
# 要素数取得
s1.size

5

In [51]:
len(s1)

5

In [52]:
# indexとデータ部分に名前を付ける
s1.index.name = 'member'
s1.name = 'score'
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

### Seriesの四則演算

In [55]:
# Seiresのすべてのデータに2が足される
s1 + 2

member
sato         92
suzuki       80
takahashi    67
tanaka       89
ito          74
Name: score, dtype: int64

In [56]:
s1 - 2

member
sato         88
suzuki       76
takahashi    63
tanaka       85
ito          70
Name: score, dtype: int64

In [57]:
s1 * 2

member
sato         180
suzuki       156
takahashi    130
tanaka       174
ito          144
Name: score, dtype: int64

In [58]:
s1 / 2

member
sato         45.0
suzuki       39.0
takahashi    32.5
tanaka       43.5
ito          36.0
Name: score, dtype: float64

In [59]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [62]:
# 文字列のSeriesに四則演算するとエラーになる
s5 = pd.Series(['test'])
s5 + 2


TypeError: can only concatenate str (not "int") to str

### Series同士の足し算
Series同士に同じindex名があるとできる

In [64]:
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [66]:
s2.index = ['suzuki', 'takahashi', 'tanaka', 'ito', 'watanabe']
s2

suzuki       1
takahashi    3
tanaka       5
ito          7
watanabe     9
dtype: int64

In [67]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [68]:
s1 + s2

ito          79.0
sato          NaN
suzuki       79.0
takahashi    68.0
tanaka       92.0
watanabe      NaN
dtype: float64

In [69]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [70]:
# 欠損値があるか調べる
s1.hasnans

False

In [72]:
s4 = pd.Series([90, 78, 65, None, 72]) 
s4

0    90.0
1    78.0
2    65.0
3     NaN
4    72.0
dtype: float64

In [74]:
# 欠損値があるとtrue
s4.hasnans

True

In [77]:
# どこの値がnanなのか確認
pd.isnull(s4)

0    False
1    False
2    False
3     True
4    False
dtype: bool

## DataFrameを使ってSeriesの関係を調べる

In [79]:
df = pd.DataFrame([[1,2,3], [4,5,6],[7,8,9]],
                 columns=['col01', 'col02', 'col03'],
                 index=['idx01', 'idx02', 'idx03'])
df

col01  col02  col03
idx01      1      2      3
idx02      4      5      6
idx03      7      8      9

In [84]:
# DataFrameからSeries取得
df['col01']

idx01    1
idx02    4
idx03    7
Name: col01, dtype: int64

In [85]:
# データ型を確認
type(df['col01'])

pandas.core.series.Series

In [87]:
# DataFrameにSeriesを追加
s5 = pd.Series({'idx01':10, 'idx02':11, 'idx03':12})
s5

idx01    10
idx02    11
idx03    12
dtype: int64

In [88]:
df['col04'] = s5
df

col01  col02  col03  col04
idx01      1      2      3     10
idx02      4      5      6     11
idx03      7      8      9     12

In [93]:
# index名をあえて違った場合はどうなるか
s6 = pd.Series({'idx03':13, 'idx04':14, 'idx05':15})
s6

idx03    13
idx04    14
idx05    15
dtype: int64

In [94]:
df['col05'] = s6
df

col01  col02  col03  col04  col05
idx01      1      2      3     10    NaN
idx02      4      5      6     11    NaN
idx03      7      8      9     12   13.0

### 時系列データ

In [99]:
dates = pd.date_range('2000/01/01', periods = 5, freq = 'D')
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05'],
              dtype='datetime64[ns]', freq='D')

In [100]:
type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [101]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [105]:
# インデックスを時系列データに変更
s1.index = dates
s1

2000-01-01    90
2000-01-02    78
2000-01-03    65
2000-01-04    87
2000-01-05    72
Freq: D, Name: score, dtype: int64

インデックスが時系列データになると特殊な集計ができるようになります


## 確認問題

In [108]:
name = ['sato', 'ito']
score = [90, 80]
dict01 = {'ito': 50, 'suzuki': None}
df = pd.DataFrame([[90, 75], [60, 95]],
                  index = ['sato', 'ito'],
                  columns = ['English', 'Math'])

df

English  Math
sato       90    75
ito        60    95

In [147]:
# 1.リスト型の変数を使ってSeriesを作成
s1 = pd.Series(score)
s1
s1.index = name
s1

# 短く書くなら
# s_list = pd.Series(score, name)
# s_list 

sato    90
ito     80
dtype: int64

In [148]:
# 2辞書型の変数を使ってSeries作成
s2 = pd.Series(dict01)
s2

ito       50.0
suzuki     NaN
dtype: float64

In [149]:
# 3.インデックス取得
s1.index

Index(['sato', 'ito'], dtype='object')

In [150]:
# 4.2つめに作成したSeriesの値を取得
s2.values

array([50., nan])

In [151]:
# 5.比較演算子を使って、１つ目に作ったSeriesの90点のデータを取得
s1[s1 == 90]

sato    90
dtype: int64

In [152]:
# 6.二つ目に作成したSeriesに「Nan」があるか確認
# s2.hasnans
pd.isnull(s2)

ito       False
suzuki     True
dtype: bool

In [153]:
# 7.一つ目に作成したSeriesをScienceのカラム名として、データフレームに追加
df['Science'] = s1
df

English  Math  Science
sato       90    75       90
ito        60    95       80

## 問題1
完成イメージの通りに、下記のリストからシリーズを作成してみましょう。

完成イメージ

0    90
1    78
2    65
3    87
4    72
dtype: int64


In [2]:
s1 = pd.Series([90, 78, 65, 87, 72])
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

## 問題2
下記のリストを任意の変数に代入します。
完成イメージの通りに、リストが代入された変数を使用して、シリーズを作成してみましょう。

完成イメージ

0    46
1    98
2    30
3    12
dtype: int64

In [7]:
list = [46, 98, 30, 12]
s1 = pd.Series(list)
s1

0    46
1    98
2    30
3    12
dtype: int64

## 問題3
シリーズのデータに、NumPyライブラリのarange関数で1から9までの間隔を2とする配列を指定して、シリーズを作成してみましょう。

完成イメージ

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [9]:
import numpy as np
np_data = np.arange(1, 10, 2)
s1 = pd.Series(np_data)
s1

0    1
1    3
2    5
3    7
4    9
dtype: int64

## 問題4

シリーズのデータに、NumPyライブラリのlinspace関数で2から10までで要素数を5とする配列を指定して、シリーズを作成してみましょう。

完成イメージ


0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64

In [14]:
# 参考 https://www.headboost.jp/numpy-linspace/
# 公式？ https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

np_data2 = np.linspace(2.0, 10, 5)
s2 = pd.Series(np_data2)
s2

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64

## 問題5
完成イメージの通りに、下記シリーズのデータ部分のデータ型を取得してみましょう。

完成イメージ

dtype('int64')

In [15]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72])

In [17]:
ser.dtypes

dtype('int64')

## 問題6
NumPyライブラリのarange関数を使用して、0.1から1.3までの間隔を0.2とする配列を作成します。
作成した配列をもとにシリーズを作成し、完成イメージの通りに、データ部分のデータ型を取得してみましょう。

完成イメージ

dtype('float64')


In [21]:
pd.Series(np.arange(0.1, 1.5, 0.2))
s2.dtypes

dtype('float64')

## 問題7
完成イメージの通りに、下記シリーズのインデックスを取得してみましょう。

完成イメージ

RangeIndex(start=0, stop=5, step=1)

In [22]:
# 使用データ
ser = pd.Series(np.arange(10, 20, 2))

In [24]:
ser.index

RangeIndex(start=0, stop=5, step=1)

## 問題8
完成イメージの通りに、下記シリーズにインデックスを設定してみましょう。

完成イメージ


Sato      90
Yamada    78
Suzuki    65
Tanaka    87
Ito       72
dtype: int64

In [26]:
# 使用データ
# シリーズ
ser = pd.Series([90, 78, 65, 87, 72])

# インデックス
#'Sato', 'Yamada', 'Suzuki','Tanaka','Ito'

# インデックスの変更
ser.index = ['sato', 'suzuki', 'takahashi', 'tanaka', 'ito']
ser

sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
dtype: int64

## 問題9
下記の辞書型のデータを使用して、完成イメージの通りにシリーズを作成してみましょう。

完成イメージ

Sato      90
Yamada    78
Suzuki    65
Tanaka    87
Ito       72
dtype: int64

In [27]:
# 使用データ
d = {'Sato':90, 'Yamada':78, 'Suzuki':65, 'Tanaka':87,'Ito':72}

In [29]:
ser = pd.Series(d)
ser

Sato      90
Yamada    78
Suzuki    65
Tanaka    87
Ito       72
dtype: int64

## 問題10
下記の辞書型のデータを使用してシリーズを作成します。
そして、完成イメージの通りに、シリーズのインデックスを「1,2,3,4」に変更してみましょう。

完成イメージ


1    46
2    98
3    30
4    12
dtype: int64

In [30]:
#使用データ
d = {'Python':46, 'Ruby':98, 'Java':30, 'C':12}

In [32]:
ser = pd.Series(d)
ser.index = [1, 2, 3, 4]
ser

1    46
2    98
3    30
4    12
dtype: int64

## 問題11
完成イメージの通りに、下記シリーズのデータを取得してみましょう。

完成イメージ

array([1, 3, 5, 7, 9])

In [35]:
# 使用データ
ser = pd.Series(np.arange(1, 10, 2))
ser.values

array([1, 3, 5, 7, 9])

## 問題12
完成イメージの通りに、下記シリーズの要素の78を取得してみましょう。

完成イメージ

78


In [38]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])

In [41]:
ser['suzuki']

78

## 問題13
完成イメージの通りに、下記シリーズから'suzuki'と'tanaka'のデータを取得してみましょう。

完成イメージ

suzuki    78
tanaka    87
dtype: int64

In [46]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72], index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])

# リスト
# ['suzuki','tanaka']
ser[['suzuki','tanaka']]

suzuki    78
tanaka    87
dtype: int64

## 問題14
完成イメージの通りに、下記シリーズから、80より大きいデータのみ抽出してみましょう。

完成イメージ

sato      90
tanaka    87
dtype: int64

In [50]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72], index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])
ser[ser > 80]


sato      90
tanaka    87
dtype: int64

## 問題15
完成イメージの通りに、下記シリーズから、80以下のデータのみ抽出してみましょう。

完成イメージ


suzuki       78
takahashi    65
ito          72
dtype: int64

In [52]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])
ser[ser <= 80]

suzuki       78
takahashi    65
ito          72
dtype: int64

## 問題16
完成イメージの通りに、下記シリーズから、78と等しい値を抽出してみましょう。

完成イメージ

suzuki    78
dtype: int64

In [56]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])
ser[ser == 78]

suzuki    78
dtype: int64

## 問題17
完成イメージの通りに、下記シリーズの要素数を取得してみましょう。

完成イメージ

5

In [60]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])
ser.size


5

## 問題18
完成イメージの通りに、下記シリーズの要素数を取得してみましょう。

完成イメージ

(5,)

In [61]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])

In [64]:
ser.shape

(5,)

## 問題19
完成イメージの通りに、下記シリーズのインデックスとカラムに名前をつけてみましょう。

完成イメージ

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64


In [71]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])

# インデックス名
# 'member'

# カラム名
# 'score'
ser.index.name = 'member'
ser.name = 'score'
ser

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

## 問題20
下記シリーズの全ての要素に整数の2を足して、完成イメージの通りに表示させてみましょう。

完成イメージ



sato         92
suzuki       80
takahashi    67
tanaka       89
ito          74
dtype: int64

In [76]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])
ser + 2

sato         92
suzuki       80
takahashi    67
tanaka       89
ito          74
dtype: int64

## 問題21
完成イメージのように、下記シリーズの各要素と平均値の差を算出してみましょう。

完成イメージ


sato         11.6
suzuki       -0.4
takahashi   -13.4
tanaka        8.6
ito          -6.4
dtype: float64

In [77]:
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato',  'suzuki', 'takahashi', 'tanaka', 'ito'])

In [84]:
# 参考 https://deepage.net/features/pandas-mean.html
ser = ser - ser.mean()
ser

sato         11.6
suzuki       -0.4
takahashi   -13.4
tanaka        8.6
ito          -6.4
dtype: float64

## 問題22
完成イメージの通りに、下記のシリーズの各要素の偏差値を算出してみましょう。
ポイント

・偏差値の計算式は、（シリーズの各要素の値 - 平均）× 10 ÷ 標準偏差 + 50 です。

完成イメージ

sato         61.198455
suzuki       49.613846
takahashi    37.063853
tanaka       58.302303
ito          43.821542
dtype: float64

In [85]:
# 使用データ
ser = pd.Series([90, 78, 65, 87, 72],index = ['sato','suzuki', 'takahashi', 'tanaka', 'ito'])

In [91]:
# ser = (ser - ser.mean()) * 10 / 10 + 50
# ser

# 平均値の計算
# mean = ser.mean()

# 標準偏差の計算
# std = ser.std()

# 偏差値の計算
# deviation_values = (ser - mean) / std * 10 + 50

# 結果の表示
# deviation_values

(ser - ser.mean()) / ser.std() * 10 + 50

sato         61.198455
suzuki       49.613846
takahashi    37.063853
tanaka       58.302303
ito          43.821542
dtype: float64

## 問題23
完成イメージの通りに、シリーズser1とシリーズser2のデータを足し算してみましょう。

完成イメージ


ito          144.0
sato           NaN
suzuki       145.0
takahashi    163.0
tanaka       142.0
watanabe       NaN
dtype: float64


In [93]:
#使用データ
ser1 = pd.Series([90, 78, 65, 87, 72],index = ['sato', 'suzuki', 'takahashi', 'tanaka', 'ito'])
ser2 = pd.Series([67, 98, 55, 72, 88],index = ['suzuki', 'takahashi', 'tanaka', 'ito', 'watanabe'])
ser1 + ser2

ito          144.0
sato           NaN
suzuki       145.0
takahashi    163.0
tanaka       142.0
watanabe       NaN
dtype: float64

## 問題24

シリーズser1とシリーズser2の各要素の引き算の結果が、それぞれ10未満であるか否かの結果を、完成イメージの通りに抽出してみましょう。
ポイント

・欠損値の場合は条件を満たさないと判定します



完成イメージ

ito          False
sato         False
suzuki        True
takahashi     True
tanaka        True
watanabe     False
dtype: bool


In [103]:
# 使用データ
ser1 = pd.Series([80, 65, 88, 72, 97],index = ['sato', 'suzuki', 'takahashi', 'tanaka', 'ito'])
ser2 = pd.Series([64, 90, 74, 77, 82],index = ['suzuki', 'takahashi', 'tanaka', 'ito', 'watanabe'])
res = ser1- ser2
res < 10

ito          False
sato         False
suzuki        True
takahashi     True
tanaka        True
watanabe     False
dtype: bool

## 問題25
下記シリーズser1とシリーズser2の掛け算を行います。
完成イメージの通りに、掛け算の結果がNaN（欠損値）となるデータを、掛け算の結果の平均値で置換してみましょう。

完成イメージ


A    2000.0
B    3100.0
C    3500.0
D    3750.0
E    3150.0
F    3100.0
dtype: float64

In [114]:
# 使用データ
ser1 = pd.Series([100, 120, 100, 750, 70],index = ['A', 'B', 'C', 'D', 'E'])
ser2 = pd.Series([20, 35, 5, 45, 15],index = ['A', 'C', 'D', 'E', 'F'])
ser3 = ser1 * ser2
ser3.fillna(ser3.mean())

A    2000.0
B    3100.0
C    3500.0
D    3750.0
E    3150.0
F    3100.0
dtype: float64

## 問題26
完成イメージの通りに、下記シリーズのデータに欠損値が含まれるかどうかを判定してみましょう。

完成イメージ

True

In [117]:
# 使用データ
ser = pd.Series([90, 78, 65, None, 72])
ser.hasnans

True

## 問題27
完成イメージの通りに、下記シリーズの各要素が欠損値であるか否かを判定してみましょう。

完成イメージ

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [118]:
# 使用データ
ser = pd.Series([ None, 'Suzuki', 'tanaka', None, 'ito'])

In [120]:
ser.isnull()

0     True
1    False
2    False
3     True
4    False
dtype: bool

## 問題28
完成イメージの通りに、下記シリーズのデータに含まれる欠損値の数を取得してみましょう。

完成イメージ

2

In [124]:
# 使用データ
ser = pd.Series([60, 80, None, None, 88])
ser.isnull().sum()

2

## 問題29
完成イメージの通りに、下記データフレームから'col01'列をシリーズとして抽出してみましょう。

完成イメージ

idx01    1
idx02    4
idx03    7
Name: col01, dtype: int64

In [127]:
# 使用データフレーム
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  columns=['col01', 'col02', 'col03'],
                  index=['idx01', 'idx02', 'idx03'])
df

col01  col02  col03
idx01      1      2      3
idx02      4      5      6
idx03      7      8      9

In [128]:
df['col01']

idx01    1
idx02    4
idx03    7
Name: col01, dtype: int64

## 問題30
下記データフレームに’col04'列として下記シリーズを追加してみましょう。

In [132]:
# データフレーム
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  columns=['col01', 'col02', 'col03'],
                  index=['idx01', 'idx02', 'idx03'])
# シリーズ
ser = pd.Series({'idx01':10, 'idx02':11, 'idx03':12})

df['col04'] = ser
df

col01  col02  col03  col04
idx01      1      2      3     10
idx02      4      5      6     11
idx03      7      8      9     12

## 問題31
下記データフレームdf2から'col04'列を抽出し、データフレームdf01の'col04'として追加してみましょう。

In [135]:
# 使用データ
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   columns=['col01', 'col02', 'col03'],
                   index=['idx01', 'idx02', 'idx03'])

df2 = pd.DataFrame([[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   columns=['col04', 'col05', 'col06'],
                   index=['idx01', 'idx02', 'idx03'])

df1['col04'] = df2['col04']
df1

col01  col02  col03  col04
idx01      1      2      3     10
idx02      4      5      6     13
idx03      7      8      9     16

## 問題32
2000年1月1日から1月5日までの時系列データを作成します。
そして、作成した時系列データを使用して、シリーズを作成してみましょう。

完成イメージ

0   2000-01-01
1   2000-01-02
2   2000-01-03
3   2000-01-04
4   2000-01-05
dtype: datetime64[ns]

In [139]:
# 使用データ
# '2000/01/01'
dates = pd.date_range('2000/01/01', periods = 5, freq = 'd')
ser = pd.Series(dates)
ser


0   2000-01-01
1   2000-01-02
2   2000-01-03
3   2000-01-04
4   2000-01-05
dtype: datetime64[ns]

## 問題33

2000年1月から6月までの1日の時系列データを作成します。
そして、完成イメージの通りに、作成した時系列データを下記シリーズのインデックスに指定してみましょう。

完成イメージ

2000-01-01    990
2000-02-01    650
2000-03-01    480
2000-04-01    500
2000-05-01    750
2000-06-01    800
Freq: MS, dtype: int64

In [155]:
# 使用データ
ser = pd.Series([990, 650, 480, 500, 750, 800])
# 時系列データの開始日 '2000/01/01'
dates = pd.date_range('2000/01/01', periods=6, freq='MS')
ser.index = dates
ser

2000-01-01    990
2000-02-01    650
2000-03-01    480
2000-04-01    500
2000-05-01    750
2000-06-01    800
Freq: MS, dtype: int64