# Numpy関数・メソッド
NumPyは、プログラミング言語Pythonにおいて数値計算を効率的に行うための拡張モジュールである。効率的な数値計算を行うための型付きの多次元配列のサポートをPythonに加えるとともに、それらを操作するための大規模な高水準の数学関数ライブラリを提供する。

In [1]:
import numpy as np

## 配列の作成 | numpy.arange関数

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1, 10, 2) # 1以上10未満、間隔が2

array([1, 3, 5, 7, 9])

In [4]:
np.arange(-1, -10, -2)

array([-1, -3, -5, -7, -9])

In [5]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

## 配列の作成 | numpy.linspace関数
等間隔の配列を作成

In [6]:
np.linspace(1, 20) # デフォルトの要素数は50

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [7]:
np.linspace(1, 20, 10) # 要素数10の配列を作成

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [8]:
np.linspace(1, 20, 5, retstep=True) # 各要素の差分取得 引数にretstep=Trueを渡す

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), 4.75)

In [9]:
np.linspace(1, 20, 5, endpoint=False) # 最後の要素を含まず配列を作成

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

## 配列の作成 | numpy.zeros/ones関数
Pythonで全ての要素が0や１の配列を作成

In [10]:
np.zeros(7) # すべての値が0の配列作成

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((2, 4)) # すべて1 行数、列数

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros(7).dtype # zeros onesともにデフォルトのデータ型はfolat64

dtype('float64')

In [13]:
np.zeros(7, dtype=int).dtype

dtype('int64')

In [14]:
# 任意の数値で変えたい場合 第一引数:要素数 第二引数:数値
np.full(5, 10.5)

array([10.5, 10.5, 10.5, 10.5, 10.5])

## 配列の作成 | numpy.empty関数
Pythonで要素を指定せずに配列を作成

In [15]:
np.empty(5)

array([10.5, 10.5, 10.5, 10.5, 10.5])

In [16]:
np.empty((2, 3)) # 二次元配列

array([[4.26690914e-310, 5.30276956e+180, 4.42132230e-062],
       [6.98341113e-076, 3.25510388e-086, 3.35658854e-143]])

In [17]:
np.empty((2, 3), dtype=int) # 要素を指定しない分高速

array([[     86363202387968, 7310593858020254331, 3689064036650590820],
       [3482469096215687213, 3328213151118408241, 2475346132171174456]])

## 配列の作成 | numpy.identity/eye関数
Pythonで単位行列を作成する

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.identity(3, 5) # 列数と行数を別々に指定するとエラーになる

TypeError: data type not understood

In [20]:
np.eye(3, M=5, k=2) # 引数1:行数 引数2:列数 引数3:対角線の開始位置

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 配列の作成 | numpy.meshgrid関数
Pythonで配列から座標の格子点を作成する方法

In [28]:
import numpy as np
a = np.array([0,1,2,3])
b = np.array([0,1,2])
print(f'a:{a}')
print(f'b:{b}')
print('---------------')
X, Y = np.meshgrid(a, b) # 返り値は交点のX軸・Ý軸座標
 

a:[0 1 2 3]
b:[0 1 2]
---------------


In [32]:
X # 2つの配列の交点のX座標が代入

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [34]:
Y # 2つの配列の交点のy座標が代入

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [35]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 1, 2])
a

array([0, 1, 2, 3])

In [36]:
X, Y = np.meshgrid(a, b)

In [44]:
print('X座標')
print(X)
print('Y座標')
print(Y)
# 補足 座標の格子点は主に等高線や三次元のグラフを作成する時に使用されます。

X座標
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
Y座標
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


## 配列の結合｜numpy.concatenate関数


In [48]:
a_1 = np.array([[5, 5, 5], [5, 5, 5]])
b_1 = np.array([[10, 10, 10], [10, 10, 10]])

In [50]:
np.concatenate([a_1, b_1]) # 行方向に結合

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10]])

In [54]:
a_1 = np.array([[5, 5, 5], [5, 5, 5]])
b_1 = np.array([[10, 10, 10], [10, 10, 10]])
np.concatenate([a_1, b_1], axis=1) # 列方向に結合

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

In [56]:
a_1 = np.array([[5, 5, 5], [5, 5, 5]])
b_1 = np.array([[10, 10, 10], [10, 10, 10]])
c_1 = np.array([[20, 20, 20], [20, 20, 20]])
np.concatenate([a_1, b_1, c_1])

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10],
       [20, 20, 20],
       [20, 20, 20]])

## 配列の結合｜numpy.hstack関数
Pythonで配列を横方向に結合する方法

In [61]:
a_1 = np.array([2, 8, 5])
a_2 = np.array([30, 60, 10])
np.hstack((a_1, a_2)) # 合する配列の行数が異なるとエラーとなる

array([ 2,  8,  5, 30, 60, 10])

In [62]:
a_3 = np.array([[3, 6, 2, 5], [4, 1, 7, 5], [3, 5, 8, 5]])
a_4 = np.array([[40, 20, 70], [90, 10, 60], [80, 30, 50]])
np.hstack((a_3, a_4))

array([[ 3,  6,  2,  5, 40, 20, 70],
       [ 4,  1,  7,  5, 90, 10, 60],
       [ 3,  5,  8,  5, 80, 30, 50]])

In [64]:
# 似たような関数でvstackがある（縦方向に配列を結合）
a_1 = np.array([1, 2, 3, 4, 5])
a_2 = np.array([10, 20, 30, 40, 50])
np.vstack((a_1, a_2))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## 配列の結合｜numpy. vstack関数
Pythonで配列を縦方向に結合する方法

In [66]:
a_1 = np.array([1, 2, 3, 4, 5])
a_2 = np.array([10, 20, 30, 40, 50])
np.vstack((a_1, a_2))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [70]:
a_1 = np.array([1, 2, 3, 4, 5])
a_3 = np.array([[60, 61, 62, 63, 64], [70, 71, 72, 73, 74], [80, 81, 82, 83, 84]])
np.vstack((a_1, a_3)) # 行数の異なる配列同士でも、列数が同じであれば縦方向に結合することができる

array([[ 1,  2,  3,  4,  5],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84]])

In [71]:
a_1 = np.array([1, 2, 3, 4, 5])
a_2 = np.array([10, 20, 30, 40, 50])
a_3 = np.array([[60, 61, 62, 63, 64], [70, 71, 72, 73, 74], [80, 81, 82, 83, 84]])
np.vstack((a_1, a_2, a_3))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84]])

## 配列の結合｜numpy. stack関数
Pythonで配列を新たな次元で結合する方法

In [77]:
a = np.array([1, 2, 3])
np.stack([a, a]) # 一次元配列が2次元配列になる

array([[1, 2, 3],
       [1, 2, 3]])

In [80]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.stack([b, b]) # 次元配列どうしを結合した場合は、3次元配列に

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [82]:
# 1次元配列を次元を変えずに横方向に結合
a = np.array([1, 2, 3])
np.concatenate([a, a])

array([1, 2, 3, 1, 2, 3])

## 配列の結合｜numpy. block関数
Pythonで配列を任意の方向に結合する方法

In [84]:
a = np.array([[1, 2], [3, 4]])
np.block([a, a])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [86]:
a = np.array([[1, 2], [3, 4]])
np.block([[a], [a]])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [94]:
# 2次元配列を結合した3次元配列を作成
a = np.array([[1, 2], [3, 4]])
np.block([[[a]], [[a]]])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [98]:
a = np.array([[1, 2], [3, 4]])
np.block([[a, a], [a, a]])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

## 配列の結合｜numpy. repeat関数
Pythonで配列の要素を繰り返す方法

In [100]:
a = np.array([1, 2, 3])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [101]:
b = np.array([[1, 2], [3, 4]])
np.repeat(b, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [104]:
b = np.array([[1, 2], [3, 4]])
np.repeat(b, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [107]:
b = np.array([[1, 2], [3, 4]])
np.repeat(b, 2,  axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## 配列の結合｜numpy. tile関数
Pythonで配列タイル状に繰り返す方法

In [114]:
a = np.array([1, 2, 3])
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [119]:
a = np.array([1, 2, 3])
np.tile(a, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [120]:
a = np.array([1, 2, 3])
np.tile(a, (2, 2, 2))

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]])

## 配列の変換・並び替え｜numpy.reshape関数
Pythonで配列の形状を変換する方法

In [122]:
a = np.array([1, 5, 12, 0, 5, 1])
np.reshape(a, (2, 3)) # 縦方向に2,横方向に3の二次元配列に

array([[ 1,  5, 12],
       [ 0,  5,  1]])

In [125]:
a = np.array([1, 5, 12, 0, 5, 1])
np.reshape(a, (3, 1, 2)) # 三次元配列に

array([[[ 1,  5]],

       [[12,  0]],

       [[ 5,  1]]])

In [124]:
np.reshape(a, (2, -1)) # -1を設定すると適切にしてくれる

array([[ 1,  5, 12],
       [ 0,  5,  1]])

## 配列の変換・並び替え｜numpy.transpose関数
Pythonで配列の軸を変換する方法

In [128]:
a_1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.transpose(a_1) # 縦方向と横方向の軸を入れ替え

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [132]:
a_2 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]]])
np.transpose(a_2, (0, 1, 2)) # 0:0軸 1:1軸 2:2軸 / 0:深さ 1:縦 2:横 0,1,2の場合そのまま同じ配列が返ってくる

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [134]:
a_2 = np.array([[[1, 2, 3, 4]],
                [[5, 6, 7, 8]],
                [[9, 10, 11, 12]]])
np.transpose(a_2, (0, 1, 2)).shape


(3, 1, 4)

In [140]:
a_2 = np.array([[[1, 2, 3, 4]],
                [[5, 6, 7, 8]],
                [[9, 10, 11, 12]]])
print(np.transpose(a_2, (2, 1, 0))) # 横、縦、深さの軸順に入れ替え
print(np.transpose(a_2, (2, 1, 0)).shape)

[[[ 1  5  9]]

 [[ 2  6 10]]

 [[ 3  7 11]]

 [[ 4  8 12]]]
(4, 1, 3)


In [146]:
a_2 = np.array([[[1, 2, 3, 4]],
                [[5, 6, 7, 8]], 
                [[9, 10, 11, 12]]])
np.transpose(a_2, (0, 2, 1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

## 配列の変換・並び替え｜numpy.flatten関数
Pythonで多次元配列を一次元配列に変換する方法

In [152]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.flatten() # 行を優先して一次元配列に変換する

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
a.flatten(order='F') # 列を優先して一次元配列を作成

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [156]:
c = a.ravel()
c #配列のメモリを参照（配列のあるメモリの場所を返します）
# 補足としてflattenメソッドは配列を新たに作成

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
b = a.flatten()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
b[0]= 10
a # 元の値は変わらない

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
c = a.ravel()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
c[0] = 10
a # ravelでは値が変わる

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## 配列の変換・並び替え｜numpy.clip関数
Pythonで配列の最小値・最大値を設定する方法

In [168]:
a = np.array([1, 2, 3, 4, 5, 6])
np.clip(a, 2, 5)

array([2, 2, 3, 4, 5, 5])

In [169]:
np.clip(a, 2, None) # 最小値のみ

array([2, 2, 3, 4, 5, 6])

In [170]:
np.clip(a, 2, 5, out=a) # outを設定すると渡した変数の値が上書きされる
a

array([2, 2, 3, 4, 5, 5])

## 配列の変換・並び替え｜numpy.sort,argsort関数
Pythonで配列を昇順に並び替える方法

In [171]:
a = np.array([20, 30, 50, 60, 10, 40])
np.sort(a)

array([10, 20, 30, 40, 50, 60])

In [173]:
a = np.array([20, 30, 50, 60, 10, 40])
np.argsort(a)

array([4, 0, 1, 5, 2, 3])

In [174]:
b = np.array([[10, 2, 30, 4],
              [1, 20, 3, 40]])
np.sort(b, axis=0)

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [175]:
b = np.array([[10, 2, 30, 4],
              [1, 20, 3, 40]])
np.sort(b, axis=1)

array([[ 2,  4, 10, 30],
       [ 1,  3, 20, 40]])

In [179]:
b = np.array([[10, 2, 30, 4],
              [1, 20, 3, 40]])
np.sort(b, None) # Noneを指定することで一次元配列に
# np.sort(b, axis=None) # これも同じ結果にaxis=Noneと記載した方がよい？？

array([ 1,  2,  3,  4, 10, 20, 30, 40])

## 配列の変換・並び替え｜numpy. histogram関数
Pythonで配列からヒストグラムを作成する方法

In [189]:
# ヒストグラムは、統計やデータ解析において使用される視覚化の手法
np.random.seed(0)
a = np.random.randint(0, 11, size=50) # 配列を10分割　最小値と最大値を含む境界値11個
a

array([ 5,  0,  3,  3,  7,  9,  3,  5,  2,  4,  7,  6,  8,  8, 10,  1,  6,
        7,  7,  8,  1,  5,  9,  8,  9,  4,  3,  0,  3,  5,  0,  2,  3,  8,
        1,  3,  3,  3,  7,  0,  1,  9,  9,  0, 10,  4,  7,  3,  2,  7])

In [185]:
np.histogram(a) # 要素数と境界値を取得 一つ目は要素数 二つ目が境界値

(array([ 5,  4,  3, 10,  3,  4,  2,  7,  5,  7]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [188]:
np.histogram(a, bins=5)

(array([ 9, 13,  7,  9, 12]), array([ 0.,  2.,  4.,  6.,  8., 10.]))

In [191]:
np.histogram(a, density=True) # 確率密度

(array([0.1 , 0.08, 0.06, 0.2 , 0.06, 0.08, 0.04, 0.14, 0.1 , 0.14]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

## 配列の要素の追加・置換｜numpy. append関数
Pythonで配列の末尾に要素を追加する方法

In [193]:
a_1 = np.array([1, 2, 3, 4, 5])
np.append(a_1, 100)

array([  1,   2,   3,   4,   5, 100])

In [195]:
a_1 = np.array([1, 2, 3, 4, 5])
np.append(a_1, [50, 55, 60])

array([ 1,  2,  3,  4,  5, 50, 55, 60])

In [196]:
a_2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.append(a_2, 100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [199]:
a_2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
b = np.array([[10, 20, 30]])
np.append(a_2, b, axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [201]:
a_2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
c = np.array([[10], [20], [30]])
np.append(a_2, c, axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

## 配列の要素の追加・置換｜numpy.put関数
Pythonで配列のインデックスを指定して値を置換する方法

In [204]:
a = np.array([1, 5, 12, 0, 5, 1])
np.put(a, 1, 500)
a

array([  1, 500,  12,   0,   5,   1])

In [206]:
a = np.array([1, 5, 12, 0, 5, 1])
np.put(a, [0, 1, 2], [10, 20, 30])
a

array([10, 20, 30,  0,  5,  1])

In [207]:
# 先頭の要素の値を200に置換 なお、指定したインデックスの値が配列のインデックスの最大値を上回るように設定
a = np.array([1, 5, 12, 0, 5, 1])
np.put(a, 6, 200, mode="wrap")
a

array([200,   5,  12,   0,   5,   1])

In [208]:
# 末尾の要素の値を200に置換 なお、指定したインデックスの値が配列のインデックスの最大値を上回るように設定
a = np.array([1, 5, 12, 0, 5, 1])
np.put(a, 6, 200, mode="clip")
a

array([  1,   5,  12,   0,   5, 200])

## 配列の要素の追加・置換｜numpy. putmask関数
Pythonで配列の値を条件を指定して置換する方法

In [213]:
a_1 = np.array([1, 5, 2, 6, 8, 3, 4])
np.putmask(a_1, a_1 >= 5, 100) # 引数1:対象値, 引数2:条件, 引数3:書き換える値
a_1

array([  1, 100,   2, 100, 100,   3,   4])

In [214]:
a_2 = np.array([[1, 7, 5],
                [4, 3, 8],
                [12, 2, 1]])
np.putmask(a_2, a_2 >= 5, 100)
a_2

array([[  1, 100, 100],
       [  4,   3, 100],
       [100,   2,   1]])

In [216]:
a_2 = np.array([[1, 7, 5],
                [4, 3, 8],
                [12, 2, 1]])
np.putmask(a_2, a_2 >= 5, [100, 10]) # 2次元配列の要素のうち、5以上の値を全て100と10に交互に置換
a_2

array([[  1,  10, 100],
       [  4,   3,  10],
       [100,   2,   1]])

## 配列の要素や値などの取得・算出｜numpy.mean,nanmean関数
Pythonで配列の平均を算出する方法

In [217]:
a_1 = np.array([1, 5, 12, 0, 5, 1])
np.mean(a_1)

4.0

In [221]:
a_2=np.array([[1, 5, 12], [0, 5, 1]])
np.mean(a_2, axis=1)

array([6., 2.])

In [222]:
a_2=np.array([[1, 5, 12], [0, 5, 1]])
np.mean(a_2, axis=0) # 2次元配列の列ごとの平均値

array([0.5, 5. , 6.5])

In [224]:
a_3 = np.array([1, 5, 12, 0, 5, np.nan])
np.nanmean(a_3) # 欠損値が含まれる配列の要素の平均値を算出

4.6

## 配列の要素や値などの取得・算出｜numpy. average関数
Pythonで配列の単純平均・加重平均を取得する方法

In [225]:
a = np.array([1, 5, 12, 0, 5, 1])
np.average(a)

4.0

In [227]:
a = np.array([1, 5, 12, 0, 5, 1])
w = np.array([0.4, 0.2, 0.1, 0.5, 0.2, 0.4]) # 重み
np.average(a, weights=w) # 1次元配列の加重平均

2.222222222222222

In [229]:
np.mean(a) # 似た関数でmeanがあるが、単純平均を求めることができるが加重平均は求めることができない

4.0

## 配列の要素や値などの取得・算出｜numpy. median関数
Pythonで配列の中央値を取得する方法

In [230]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.median(a)

4.5

In [234]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.median(a, axis=0) # 列ごとの中央値を取得

array([3., 4., 5., 6.])

In [236]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.median(a, axis=1)

array([2.5, 6.5])

In [240]:
# 欠損値が含まれる下記の1次元配列の中央値を取得
b = np.array([1, np.nan, 3, 4])
np.nanmedian(b)

3.0

## 配列の要素や値などの取得・算出｜numpy.sum/var/std関数
Pythonで配列に合計、分散、標準偏差を取得する方法

In [248]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
np.sum(a)

36

In [249]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
np.sum(a, axis=0)

array([ 6,  8, 10, 12])

In [250]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
np.sum(a, axis=1)

array([10, 26])

In [251]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
np.var(a) # 分散値

5.25

In [253]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
np.std(a) # 標準偏差

2.29128784747792

## 配列の要素や値などの取得・算出｜numpy.ndarray.max/min関数
Pythonで配列の最大値、最小値を取得する方法

In [254]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.max(a)

9

In [255]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.min(a)

1

In [259]:
# 二次元配列の列ごとの最大値を取得 axis=0が行 axis=1が列
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.max(a, axis=0)

array([7, 8, 9])

In [261]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.min(a, axis=0)

array([1, 2, 3])

In [262]:
# 2次元配列の行ごとの最大値を取得
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.max(a, axis=1)

array([3, 6, 9])

In [263]:
# 2次元配列の行ごとの最小値を取得
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.min(a, axis=1)

array([1, 4, 7])

In [265]:
# 2次元配列の最大値を取得
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.amax(a)

9

In [266]:
# 2次元配列の最小値を取得
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.amin(a)

1

## 配列の要素や値などの取得・算出｜numpy.nanmax,nanmin関数
Pythonで欠損値のある配列の最大値・最小値を取得する方法

In [269]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmax(a)

8.0

## 配列の要素や値などの取得・算出｜numpy.argmax,argmin関数
Pythonで配列の最大値・最小値のインデックスを取得する方法

In [270]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmin(a)

1.0

In [272]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmax(a, axis=0)

array([7., 8., 6.])

In [273]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmin(a, axis=0)

array([1., 2., 3.])

In [275]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmax(a, axis=1)

array([3., 6., 8.])

In [276]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, np.nan]])
np.nanmin(a, axis=1)

array([1., 4., 7.])

## 配列の要素や値などの取得・算出｜numpy.argmax,argmin関数
Pythonで配列の最大値・最小値のインデックスを取得する方法

In [278]:
# 1次元配列の最大値のインデックスを取得
a_1 = np.array([10, 23, 53, 33, 42, 19])
np.argmax(a_1)

2

In [279]:
# 1次元配列の最小値のインデックスを取得
a_1 = np.array([10, 23, 53, 33, 42, 19])
np.argmin(a_1)

0

In [280]:
a_2 = np.array([10, 23, 53, 33, 53, 19])
np.argmax(a_2)

2

In [282]:
a_3 = np.array([10, 23, 53, 33, 53, 19])
np.argmin(a_3)

0

In [285]:
a_4 = np.array([[10, 32, 22, 19, 29],
                [22, 49, 18, 53, 27]])
np.argmax(a_4)

8

In [288]:
# 2次元配列の行ごとの最大値のインデックスを取得
a_4 = np.array([[10, 32, 22, 19, 29],
                [22, 49, 18, 53, 27]])
np.argmax(a_4, axis=1)

array([1, 3])

In [290]:
# 2次元配列の行ごとの最小値のインデックスを取得
a_4 = np.array([[10, 32, 22, 19, 29],
                [22, 49, 18, 53, 27]])
np.argmin(a_4, axis=1) # axis=が無くても同様の挙動になる

array([0, 2])

## 配列の要素や値などの取得・算出｜numpy.abs関数
Pythonで配列の絶対値を取得する方法

In [291]:
a = np.array([-2, 5, -8, -1, -3])
np.abs(a)

array([2, 5, 8, 1, 3])

In [296]:
# 1次元配列の各要素の絶対値を取得
a = np.array([-2.7, 1.9, -3.4])
np.abs(a)

array([2.7, 1.9, 3.4])

In [298]:
# -3の絶対値
np.abs(-3)

3

In [299]:
# ストの各要素の絶対値を取得
np.abs([-1, 0, 1])

array([1, 0, 1])

## 配列の要素や値などの取得・算出｜numpy.maximum/fmax関数
Pythonで配列やリストを比較して最大値を取得する方法

In [304]:
# 2つの1次元配列の各要素を比較し、各要素の最大値を持つ配列を取得
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.maximum(a_1, a_2)

array([3, 5, 9])

In [311]:
# 2つの1次元配列の各要素を比較し、欠損値を除く各要素の最大値を持つ配列を取得
a_1 = np.array([2, 5, 9])
a_3 = np.array([5, np.nan, 3])
np.fmax(a_1, a_3)

array([5., 5., 9.])

In [313]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.minimum(a_1, a_2)

array([2, 1, 7])

In [315]:
## 2つの1次元配列の各要素を比較し、欠損値を除く各要素の最小値を持つ配列を取得
a_1 = np.array([2, 5, 9])
a_3 = np.array([5, np.nan, 3])
np.fmin(a_1, a_3)

array([2., 5., 3.])

## 配列の要素や値などの取得・算出｜numpy.minimum/fmin関数
Pythonで配列やリストを比較して最小値を取得する方法

In [318]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.minimum(a_1, a_2)

array([2, 1, 7])

In [319]:
a_1 = np.array([2, 5, 9])
a_3 = np.array([5, np.nan, 3])
np.fmin(a_1, a_3)

array([2., 5., 3.])

In [320]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.maximum(a_1, a_2)

array([3, 5, 9])

In [321]:
a_1 = np.array([2, 5, 9])
a_3 = np.array([5, np.nan, 3])
np.fmax(a_1, a_3)

array([5., 5., 9.])

## 配列の要素や値などの取得・算出｜numpy.add,subtract,multiply,divide関数
Pythonで配列の要素を計算（四則演算）する方法

In [323]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.add(a_1, a_2)

array([ 5,  6, 16])

In [324]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.subtract(a_1, a_2)

array([-1,  4,  2])

In [325]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.multiply(a_1, a_2)

array([ 6,  5, 63])

In [326]:
a_1 = np.array([2, 5, 9])
a_2 = np.array([3, 1, 7])
np.divide(a_1, a_2)

array([0.66666667, 5.        , 1.28571429])

## 配列の要素や値などの取得・算出｜numpy.corrcoef関数
Pythonで相関関係を取得する方法

In [331]:
a = np.array([[150, 160, 170, 180, 190],
              [55, 60, 65, 60, 70]])
np.corrcoef(a)

array([[1.        , 0.83205029],
       [0.83205029, 1.        ]])

In [332]:
a = np.array([[150, 160, 170, 180, 190],
              [55, 60, 65, 60, 70]])
b = np.array([60, 85, 55, 60, 70])
np.corrcoef(a, b)

array([[ 1.        ,  0.83205029, -0.06622662],
       [ 0.83205029,  1.        ,  0.05510388],
       [-0.06622662,  0.05510388,  1.        ]])

## 配列の要素や値などの取得・算出｜numpy.cov関数
Pythonで分散共分散行列を取得する方法

In [337]:
a = np.array([[150, 160, 170, 180, 190], [55, 60, 65, 60, 70]])
"""
1列の成分が身長の分散
2行2列の成分が体重の分散
1行2列または2行1列の成分が身長と体重の共分散
"""
np.cov(a)

array([[250. ,  75. ],
       [ 75. ,  32.5]])

In [338]:
a = np.array([[150, 160, 170, 180, 190], [55, 60, 65, 60, 70]])
b = np.array([60, 85, 55, 60, 70])
np.cov(a, b)

array([[250.  ,  75.  , -12.5 ],
       [ 75.  ,  32.5 ,   3.75],
       [-12.5 ,   3.75, 142.5 ]])

In [341]:
a = np.array([[150, 160, 170, 180, 190], [55, 60, 65, 60, 70]])
b = np.array([60, 85, 55, 60, 70])
np.cov(a, b, bias=True) # 引数にbias=Trueで標本分散になる

array([[200.,  60., -10.],
       [ 60.,  26.,   3.],
       [-10.,   3., 114.]])

## 配列の要素や値などの取得・算出｜numpy.all関数
Pythonで配列の値が条件に一致するかを判定する方法

In [342]:
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a)

False

In [346]:
# 次元配列に対して、列ごとに0が含まれるかどうか判定
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a, axis=0)

array([False,  True, False,  True,  True])

In [347]:
# 次元配列に対して、行ごとに0が含まれるかどうか判定
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a, axis=1)

array([ True, False, False])

In [349]:
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a < 5)

False

In [351]:
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a < 5, axis=0)

array([ True, False,  True, False,  True])

In [352]:
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1],
              [3, 8, 0, 6, 1]])
np.all(a < 5, axis=1)

array([False,  True, False])

In [355]:
# 2次元配列に対して、少なくとも1つの要素が5未満かどうか判定
a = np.array([[1, 7, 1, 3, 1],
              [0, 1, 0, 3, 1], 
              [3, 8, 0, 6, 1]])
np.any(a < 5)

True